---
language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

env:
  - EMBER_TRY_SCENARIO=ember-1.13

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g npm@^3"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
